### PR TITLE
ES Translation

### PR DESCRIPTION
**Pull request by Edu22mg**
Spanish Translation v1

### CODE REVIEW

**Comment by Edu22mg** [comment]
I have every official product of Root so I have written every line following the current content of Root's law and every official name and instructions. I hope you like my work.

**Comment by EwenDC** [comment]
Looking great! Thank you for the contribution.

Unfortunately there are some overflow issues that I'll need to resolve on my end. Hopefully I can get a chance to look at it in the coming days and get your changes merged.
image

**Comment by EwenDC** [comment]
Apologies for the delay, and thank you again for your contribution! This was the first translation that I didn't have to raise any threads on, so I appreciate your attention to detail and following of instructions (including on matching the official translations). Hope to see you again if any more translation work is required!

**Comment by Edu22mg** [comment]
Thank YOU Ewen, I hope I can help in more Spanish translations if there is more expansions or this app is improved (I hope so but I cannot help since I am not a programming expert)

**Pull request merged**
